version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shapeshifter
      - MONGO_INITDB_ROOT_PASSWORD=password123

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=shapeshifter
      - MYSQL_USER=shapeshifter
      - MYSQL_PASSWORD=password123

  api:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://shapeshifter:password123@mongodb:27017/shapeshifter
      - KNEX_URL=mysql://shapeshifter:password123@mysql:3306/shapeshifter
      - SERVER_PRIVATE_KEY=${SERVER_PRIVATE_KEY}
      - HOSTING_URL=${HOSTING_URL}
    depends_on:
      - mongodb
      - mysql

volumes:
  mongodb_data:
  mysql_data:
