version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shapeshifter
      - MONGO_INITDB_ROOT_PASSWORD=password123

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=shapeshifter
      - MYSQL_USER=shapeshifter
      - MYSQL_PASSWORD=password123

volumes:
  mongodb_data:
  mysql_data:
